Repository cloudfoundry-incubator/eirini-release, pull requests merged in 2018-11, with the labels that each got.

#15 Add link to pipeline
  README.md
Labels: in progress

#20 add version to eirini deployment
  scf/helm/cf/templates/eirini.yaml
  scf/helm/cf/values.yaml
Labels: unscheduled

#22 Fix docker/registry/certs/generator/generate.sh
  docker/registry/certs/generator/generate.sh
Labels: scheduled
