Repository cloudfoundry-incubator/eirini-release, pull requests merged in 2019-05, with the labels that each got.

#63 Remove restart policy from bits pod
  helm/eirini/templates/bits.yaml
Labels: scheduled

#72 Split staging image into three
  helm/eirini/templates/configmap.yaml
  helm/eirini/templates/deployment.yaml
  helm/eirini/values.yaml
Labels: unscheduled

#69 Separate the eirini rootfs from bits-service oci-image
  README.md
  helm/eirini/templates/bits.yaml
  helm/eirini/values.yaml
Labels: in progress

#79 Use tags for staging images
  helm/eirini/values.yaml
Labels: unscheduled
