Repository cloudfoundry-incubator/eirini-release, pull requests merged in 2019-03, with the labels that each got.

#40 Better readme
  README.md
Labels: in progress

#39 Add loadbalancer config to sample values.yml
  values.yaml
Labels: in progress

#42 Add registry_endpoint to bits configmap
  helm/eirini/templates/bits.yaml
Labels: scheduled

#44 Pin bits-service image tag to 2.25.0-dev.6
  helm/eirini/templates/bits.yaml
Labels: unscheduled

#43 add supported platform versions to the doc
  README.md
Labels: in progress

#41 Introduce configurable blobstore configuration
  helm/eirini/templates/bits.yaml
Labels: scheduled

#45 Pin bits-service image tag to 2.25.0-dev.7, containerd support
  helm/eirini/templates/bits.yaml
Labels: scheduled
