Repository cloudfoundry-incubator/eirini-release, pull requests merged in 2019-11, with the labels that each got.

#138 Fix typo in README
  README.md
Labels: in progress

#140 Update helm repository index YAML with 0.22.0 templates
  index.yaml
Labels: scheduled

#141 Update helm repository index YAML with 0.23.0 templates
  index.yaml
Labels: unscheduled

#142 Update helm repository index YAML with 1.0.0 templates
  index.yaml
Labels: unscheduled

#143 1.0 docs fixes
  README.md
Labels: unscheduled

#144 Add missing steps CertManager instructions
  docs/gke.md
Labels: unscheduled

#137 [bug/136] remove hard coded scf namespace
  helm/eirini/templates/rootfs-patcher.yml
Labels: scheduled
