Repository cloudfoundry-incubator/eirini-release, pull requests merged in 2019-08, with the labels that each got.

#104 Update helm repository index YAML with 0.15.0 templates
  index.yaml
Labels: unscheduled

#106 Cosmetic: fix a comment
  values.yaml
Labels: scheduled

#107 Document troubleshooting disk full on blobstore
  README.md
Labels: scheduled

#113 Update helm repository index YAML with 0.16.0 templates
  index.yaml
Labels: unscheduled

#109 Fix namespace for adapter
  helm/eirini/templates/networkpolicy.yml
Labels: scheduled

#119 Change bits-waiter role to allow get on deployment
  helm/eirini/templates/rootfs-patcher-service-account.yaml
Labels: in progress
