Repository cloudfoundry-incubator/eirini-release, pull requests merged in 2019-07, with the labels that each got.

#101 Update helm repository index YAML with 0.14.0 templates
  index.yaml
Labels: unscheduled

#102 Add notes on securing K8s API using Network Policy
  README.md
Labels: in progress

#95 Make smuggler wait for secrets to be generated
  helm/eirini/templates/job-secret-smuggler.yaml
Labels: scheduled
