Repository cloudfoundry-incubator/eirini-release, pull requests merged in 2020-10, with the labels that each got.

#178 Update helm repository index YAML with 1.9.0 templates
  index.yaml
Labels: unscheduled

#179 cf: Do not fail when router count is not defined
  helm/cf/templates/pdb.yml
Labels: scheduled

#180 cf: Do not fail when router count is not defined
  helm/cf/templates/pdb.yml
Labels: in progress
